# Generated by Django 5.2.7 on 2025-10-18 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место, где выполняется привычка', max_length=200, verbose_name='Место')),
                ('time', models.TimeField(help_text='Время, когда нужно выполнять привычку', verbose_name='Время выполнения')),
                ('action', models.CharField(help_text='Действие, которое представляет собой привычка', max_length=200, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Является ли привычка приятной (способ вознаграждения)', verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(default=1, help_text='Периодичность выполнения (от 1 до 7 дней)', verbose_name='Периодичность (дни)')),
                ('reward', models.CharField(blank=True, help_text='Чем вознаградить себя после выполнения', max_length=200, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveIntegerField(help_text='Время, которое потратит пользователь (макс 120 сек)', verbose_name='Время на выполнение (секунды)')),
                ('is_public', models.BooleanField(default=False, help_text='Доступна ли привычка другим пользователям', verbose_name='Публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, связанная с полезной', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(help_text='Создатель привычки', on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='habits_habi_user_id_c66d7a_idx'), models.Index(fields=['is_public', '-created_at'], name='habits_habi_is_publ_e50d05_idx')],
            },
        ),
    ]
